//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputActions/BoatInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BoatInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BoatInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BoatInputs"",
    ""maps"": [
        {
            ""name"": ""BoatMovements"",
            ""id"": ""7f84dda0-e45c-4cd4-b8b2-97b9955aee22"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""1967084e-564b-49fd-a123-91aef3651556"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WAD"",
                    ""id"": ""e250aa49-c7f8-4af5-a247-f24424c7b9fb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""98806425-ff08-40cc-8580-985d018b4182"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9f62ecd5-be2b-4dde-b64a-50beddae88ac"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e913c5e5-17ce-45c5-b66c-5268a66df85a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f9b0352e-306b-4d07-aeca-b1ec4cb2f886"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BoatMovements
        m_BoatMovements = asset.FindActionMap("BoatMovements", throwIfNotFound: true);
        m_BoatMovements_Move = m_BoatMovements.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BoatMovements
    private readonly InputActionMap m_BoatMovements;
    private IBoatMovementsActions m_BoatMovementsActionsCallbackInterface;
    private readonly InputAction m_BoatMovements_Move;
    public struct BoatMovementsActions
    {
        private @BoatInputs m_Wrapper;
        public BoatMovementsActions(@BoatInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_BoatMovements_Move;
        public InputActionMap Get() { return m_Wrapper.m_BoatMovements; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BoatMovementsActions set) { return set.Get(); }
        public void SetCallbacks(IBoatMovementsActions instance)
        {
            if (m_Wrapper.m_BoatMovementsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_BoatMovementsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_BoatMovementsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_BoatMovementsActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_BoatMovementsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public BoatMovementsActions @BoatMovements => new BoatMovementsActions(this);
    public interface IBoatMovementsActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
